apiVersion: v2
name: lineage-event-handler
version: 0.1.0
dependencies:
  - name: metadata-event-handler
    alias: lineage-event-handler
    version: "0.1.1"
    repository: https://pilotdataplatform.github.io/helm-charts/
