apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: superset-keycloak
  labels:
    {{- include "superset-stack.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: superset-keycloak
  data:
    - secretKey: KEYCLOAK_CLIENT_ID
      remoteRef:
        key: secret/data/superset/{{ .Values.projectName }}
        property: keycloak-client-id
    - secretKey: KEYCLOAK_SECRET
      remoteRef:
        key: secret/data/superset/{{ .Values.projectName }}
        property: keycloak-client-secret
    - secretKey: SUPERSET_SECRET_KEY
      remoteRef:
        key: secret/data/superset/{{ .Values.projectName }}
        property: superset-secret-key
