apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: atlas-storage
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 5Gi
