dataops-service:
  image:
    repository: n47w5524.c1.de1.container-registry.ovh.net/hdc-services-image/dataops
    pullPolicy: IfNotPresent
    # tag comes from versions.yaml via valueFile merge

  fullnameOverride: dataops
  replicaCount: 1

  container:
    port: 5063

  service:
    type: ClusterIP
    port: 5063

  imagePullSecrets:
    - name: docker-registry-secret

  appConfig:
    env: prod
    config_center_enabled: "false"
    config_center_base_url: ""

  extraEnv:
    HOST: "0.0.0.0"
    RDS_HOST: "postgres.utility"
    RDS_PORT: "5432"
    RDS_NAME: "dataops"
    RDS_USERNAME: "dataops_user"
    RDS_SCHEMA: "public"
    RDS_ECHO_SQL_QUERIES: "false"
    REDIS_HOST: "redis-master.redis"
    REDIS_PORT: "6379"
    REDIS_DB: "0"
    WORKERS: "2"
    LINEAGE_SERVICE: "http://lineage.utility:5064"
    QUEUE_SERVICE: "http://queue-producer.greenroom:6060"
    METADATA_SERVICE: "http://metadata.utility:5066"
    AUTH_SERVICE: "http://auth.utility:5061"
    MINIO_HOST: "http://minio.minio"
    MINIO_PORT: "9000"
    RSA_PUBLIC_KEY: "LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUE5eU9MQXlFNnd4TGJyZ2ZXNHBDM2c4a3IvY2d0L2cyZ0pOOE5pSUVGN1BtR09JQi9kMitpSDREWEtJUU42bXhLV2tEUmhLZ1dJemFLTDliNlJOTGY1alh3SHJCeElZV0h2Q01XUTdSVks5T3VzWS9oZGRpbjZseUJKbEtEK0w5RFlBTC8yUzlmaVk1TlRDU08rSnIvcTU1NVNzZFN3NUJHVWNsMlBwdXlTODNuMy9XVFJLMUV5N21MZS9QNjJSQmZnenhKUURLejBtcUZweUhRQWoveGRSQ0pzSWtvQ09HTi9nVXByQmEvVGljbkFhaWJxSEpLZVZmRXhoSUp4OC9iVHVoVENGT0hIS3A3enk3cUozNC9jUWRSSERTL2wxV0w1OXMwaXVCS1FyeHl6R1FURThITW9RT2pZTUZJUlVuTVZJUk9aOXVRbVBTYXNpSXY4NzFrR1FJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0t"

  extraEnvYaml:
    - name: RDS_PASSWORD
      valueFrom:
        secretKeyRef:
          name: dataops-credentials
          key: rds-password
    - name: REDIS_PASSWORD
      valueFrom:
        secretKeyRef:
          name: dataops-credentials
          key: redis-password

  resources:
    requests:
      cpu: 10m
      memory: 50Mi
    limits:
      cpu: 500m
      memory: 500Mi

  readinessProbe:
    tcpSocket:
      port: 5063
    initialDelaySeconds: 10
    periodSeconds: 10
    failureThreshold: 3

  livenessProbe:
    httpGet:
      path: /v1/health
      port: 5063
    periodSeconds: 30
    timeoutSeconds: 5
    failureThreshold: 3

  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
