# Database credentials — target name MUST be "xwiki-postgresql"
# Both the PG sub-chart (via existingSecret) and the XWiki deployment
# (hardcoded <release>-postgresql) read from this Secret
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: xwiki-postgresql
  namespace: utility
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: xwiki-postgresql
  data:
    - secretKey: postgresql-password
      remoteRef:
        key: secret/data/xwiki
        property: postgresql-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: xwiki-config
  namespace: utility
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: xwiki-config
  data:
    - secretKey: xwiki.cfg
      remoteRef:
        key: secret/data/xwiki
        property: xwiki-cfg
    - secretKey: xwiki.properties
      remoteRef:
        key: secret/data/xwiki
        property: xwiki-properties
