apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xwiki-data
  namespace: utility
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 5Gi
