apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: atlas-credentials
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: atlas-credentials
  data:
    - secretKey: atlas-password
      remoteRef:
        key: secret/data/atlas
        property: atlas-password
