apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: atlas-storage
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOncePod
  storageClassName: csi-cinder-high-speed
  resources:
    requests:
      storage: 5Gi
