apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: upload-credentials
  namespace: core
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: upload-credentials
  data:
    - secretKey: redis-password
      remoteRef:
        key: secret/data/redis
        property: password
    - secretKey: minio-access-key
      remoteRef:
        key: secret/data/minio
        property: access_key
    - secretKey: minio-secret-key
      remoteRef:
        key: secret/data/minio
        property: secret_key
