apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: velero-bucket-credentials
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: velero-bucket-credentials
    template:
      engineVersion: v2
      data:
        cloud: |
          [dev-backup]
          aws_access_key_id={{ .velero_bucket_access_key }}
          aws_secret_access_key={{ .velero_bucket_secret_key }}
  data:
    - secretKey: velero_bucket_access_key
      remoteRef:
        key: secret/data/velero
        property: velero-bucket-access-key
    - secretKey: velero_bucket_secret_key
      remoteRef:
        key: secret/data/velero
        property: velero-bucket-secret-key
