apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: velero-bucket-credentials
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: velero-bucket-credentials
  data:
    - secretKey: velero-bucket-access-key
      remoteRef:
        key: secret/data/velero
        property: velero-bucket-access-key
    - secretKey: velero-bucket-secret-key
      remoteRef:
        key: secret/data/velero
        property: velero-bucket-secret-key
