apiVersion: v1
kind: ConfigMap
metadata:
  name: guacamole-configuration
  labels:
    app.kubernetes.io/name: guacamole
    {{- include "guacamole-stack.labels" . | nindent 4 }}
data:
  guacamole.properties: |
    enable-environment-properties: true
    postgresql-auto-create-accounts: true
  logback.xml: |
    <configuration>
      <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
          <pattern>%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n</pattern>
        </encoder>
      </appender>
      <logger name="org.apache.guacamole" level="debug"/>
      <root level="info">
        <appender-ref ref="STDOUT"/>
      </root>
    </configuration>
