apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-credentials
  namespace: keycloak
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: keycloak-credentials
  data:
    - secretKey: admin-password
      remoteRef:
        key: secret/data/keycloak
        property: admin-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-db-credentials
  namespace: keycloak
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: keycloak-db-credentials
  data:
    - secretKey: password
      remoteRef:
        key: secret/data/keycloak
        property: keycloak-user-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-access-token
  namespace: keycloak
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: github-access-token
  data:
    - secretKey: GITHUB_TOKEN
      remoteRef:
        key: secret/data/keycloak
        property: github-token
