apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-antd
  namespace: keycloak
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: csi-cinder-high-speed
  resources:
    requests:
      storage: 1Gi
