apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pipelinewatch-job-watcher
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipelinewatch-job-watcher
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pipelinewatch-job-watcher
subjects:
  - kind: ServiceAccount
    name: pipelinewatch
    namespace: greenroom
