apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: download-credentials
  namespace: greenroom
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: download-credentials
  data:
    - secretKey: download-key
      remoteRef:
        key: secret/data/download
        property: download-key
    - secretKey: redis-password
      remoteRef:
        key: secret/data/redis
        property: password
    - secretKey: minio-access-key
      remoteRef:
        key: secret/data/minio
        property: access_key
    - secretKey: minio-secret-key
      remoteRef:
        key: secret/data/minio
        property: secret_key
