metadata-service:
  image:
    repository: n47w5524.c1.de1.container-registry.ovh.net/hdc-services-image/metadata
    pullPolicy: IfNotPresent

  fullnameOverride: metadata
  replicaCount: 1

  container:
    port: 5066

  service:
    type: ClusterIP
    port: 5066
    targetPort: 5066

  imagePullSecrets:
    - name: docker-registry-secret

  appConfig:
    port: 5066
    env: prod
    srv_namespace: metadata
    config_center_enabled: false
    METADATA_SCHEMA: metadata
    OPSDB_UTILITY_HOST: postgres.utility
    OPSDB_UTILITY_PORT: "5432"
    OPSDB_UTILITY_USERNAME: metadata_user
    DCM_PROJECT_ID: generate_id
    RUN_MIGRATIONS: "true"
    AUTH_HOST: "http://auth.utility:5061"
    KAFKA_URL: "kafka.utility:9092"
    KAFKA_TOPIC: "metadata.items"

  extraEnv:
    RSA_PUBLIC_KEY: "LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUE5eU9MQXlFNnd4TGJyZ2ZXNHBDM2c4a3IvY2d0L2cyZ0pOOE5pSUVGN1BtR09JQi9kMitpSDREWEtJUU42bXhLV2tEUmhLZ1dJemFLTDliNlJOTGY1alh3SHJCeElZV0h2Q01XUTdSVks5T3VzWS9oZGRpbjZseUJKbEtEK0w5RFlBTC8yUzlmaVk1TlRDU08rSnIvcTU1NVNzZFN3NUJHVWNsMlBwdXlTODNuMy9XVFJLMUV5N21MZS9QNjJSQmZnenhKUURLejBtcUZweUhRQWoveGRSQ0pzSWtvQ09HTi9nVXByQmEvVGljbkFhaWJxSEpLZVZmRXhoSUp4OC9iVHVoVENGT0hIS3A3enk3cUozNC9jUWRSSERTL2wxV0w1OXMwaXVCS1FyeHl6R1FURThITW9RT2pZTUZJUlVuTVZJUk9aOXVRbVBTYXNpSXY4NzFrR1FJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0t"

  extraEnvYaml:
    - name: OPSDB_UTILITY_PASSWORD
      valueFrom:
        secretKeyRef:
          name: metadata-credentials
          key: metadata-user-password

  resources:
    limits:
      cpu: "1"
      memory: 500Mi
    requests:
      cpu: 10m
      memory: 50Mi

  readinessProbe:
    failureThreshold: 3
    initialDelaySeconds: 5
    periodSeconds: 10
    successThreshold: 1
    tcpSocket:
      port: 5066

  livenessProbe:
    failureThreshold: 3
    httpGet:
      path: /v1/health
      port: 5066
      scheme: HTTP
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 3

  updateStrategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 33%
    type: RollingUpdate
